- name: Install haproxy
  yum:
    name: haproxy
    state: latest

- name: Configure haproxy controlplane
  template:
    src: templates/haproxy-controlplane.j2
    dest: /etc/haproxy/haproxy.cfg
    force: yes
    backup: yes
  when: inventory_hostname in groups.loadbalancers_controlplane

- name: Configure haproxy dataplane
  template:
    src: templates/haproxy-dataplane.j2
    dest: /etc/haproxy/haproxy.cfg
    force: yes
    backup: yes
  when: inventory_hostname in groups.loadbalancers_dataplane

- name: Update rsyslog config
  blockinfile:
    dest: /etc/rsyslog.conf
    create: yes
    block: |
      $ModLoad imudp
      $UDPServerRun 514
      $UDPServerAddress 127.0.0.1
      # Save haproxy logs to haproxy.log
      local2.* /var/log/haproxy.log

- name: Change rsyslog config to avoid haproxy logs going to messages      
  lineinfile:
      path: /etc/rsyslog.conf
      regexp: '^\*.info;mail.none;authpriv.none;cron.none\s*\/var\/log\/messages'
      line: '*.info;mail.none;authpriv.none;cron.none;local2.none    /var/log/messages'
      backrefs: true


- name: Allow port 7443 and 7080 to use httpd
  command: semanage port -a -t http_port_t -p tcp "{{ item }}"
  become: true
  with_items:
    - 7443
    - 7080
  when: inventory_hostname in groups.loadbalancers_dataplane

- name: Enable haproxy
  command: systemctl enable haproxy

- name: Restart haproxy
  command: systemctl restart haproxy

- name: Restart rsyslog
  command: systemctl restart rsyslog

- name: setup firewall - http
  firewalld:
    service: http
    immediate: true
    permanent: true
    zone: public
    state: enabled
  when: inventory_hostname in groups.loadbalancers

- name: setup firewall - https
  firewalld:
    service: https
    immediate: true
    permanent: true
    zone: public
    state: enabled
  when: inventory_hostname in groups.loadbalancers

- name: setup firewall - OpenShift API
  firewalld:
    port: 8443/tcp
    immediate: true
    permanent: true
    state: enabled
    zone: public
  when: inventory_hostname in groups.loadbalancers_controlplane

- name: Increase the max tracked connections on loadbalancers
  sysctl:
    name: net.netfilter.nf_conntrack_max
    value: 131072
    state: present
    reload: yes
  when: inventory_hostname in groups.loadbalancers

- name: Increase the port range for outgoing connections
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: 10240 65535
    state: present
    reload: yes
  when: inventory_hostname in groups.loadbalancers

- name: Create conntrack hash table file
  file:
    path: /etc/modprobe.d/nf_conntrack.conf
    owner: root
    group: root
    mode: '0644'
    state: touch
  when: inventory_hostname in groups.loadbalancers

- name: Add conntrack hash table increase to created file
  lineinfile:
    path: /etc/modprobe.d/nf_conntrack.conf
    insertbefore: BOF
    line: 'options nf_conntrack expect_hashsize=32768 hashsize=32768'
    state: present
  when: inventory_hostname in groups.loadbalancers

- name: Restart firewalld to implement change
  systemd:
    state: restarted
    name: firewalld
  when: inventory_hostname in groups.loadbalancers


    
